services:
  mysql:
    image: mysql
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE
    volumes:
      - ./.docker/mysql/conf:/etc/mysql/conf.d
      - ./volumes/mysql/dump:/docker-entrypoint-initdb.d
      - ./volumes/mysql/data:/var/lib/mysql
    ports:
      - 127.0.0.1:3306:3306
    restart: unless-stopped
    environment:
      - TZ
      - MYSQL_HOST
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
  nextcloud:
    build:
      context: .docker/app
      args:
        version_php: ${VERSION_PHP}
        version_node: ${VERSION_NODE}
        host_uid: ${UID}
        host_gid: ${GID}
    ports:
      - 127.0.0.1:8080:8080
    volumes:
      - ./.docker/app/wait-for-db.php:/var/www/scripts/wait-for-db.php
      - ./.env:/var/www/.env
      - ~/.composer:/root/.composer/
      - ~/.npm:/root/.npm/
      - ./volumes/nextcloud:/var/www/html
    restart: unless-stopped
    environment:
      - DEFAULT_PHONE_REGION
      - NEXTCLOUD_ADMIN_USER
      - NEXTCLOUD_ADMIN_PASSWORD
      - MYSQL_HOST
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
      - VERSION_NEXTCLOUD
      - AUTOINSTALL
      - XDEBUG_CONFIG
  keycloak:
    image: quay.io/keycloak/keycloak:21.0.2   
    ports:
      - 127.0.0.1:28080:8080 
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    command: start-dev
        
  cron:
    build:
      context: .docker/app
      args:
        version_php: ${VERSION_PHP}
        version_node: ${VERSION_NODE}
        host_uid: ${UID}
        host_gid: ${GID}
    volumes:
      - ./.docker/app/wait-for-db.php:/var/www/scripts/wait-for-db.php
      - ./.env:/var/www/.env
      - ./volumes/nextcloud:/var/www/html
    entrypoint: /usr/local/bin/cron.sh
  nginx:
    build: .docker/web
    restart: unless-stopped
    volumes:
      - ./volumes/nextcloud:/var/www/html:ro
      - ./volumes/nginx/includes:/etc/nginx/conf.d/includes/
    ports:
      - 127.0.0.1:${HTTP_PORT}:80
  mailhog:
    image: blueimp/mailhog
    ports:
      - 127.0.0.1:${MAILHOG_PORT}:8025
  redis:
    image: redis

networks:
  local-keycloak: